export default {
  children: [null],
  code: null,
  createTime: null,
  description: null,
  id: null,
  leaf: true,
  level: 0,
  managerId: null,
  name: null,
  organization: {
    id: null,
  },
  parentId: null,
  sortNo: 0,
  status: null,
  tenantId: 'default',
  type: null,
  updateTime: null,
}
