export default {
  address: null,
  area: null,
  children: [null],
  code: null,
  degree: null,
  description: null,
  dimension: {
    id: null,
  },
  mainDimensionOrg:{
    id : null,
  },
  email: null,
  id: null,
  leaf: true,
  strategy: null,
  level: 0,
  linkMan: null,
  linkTel: null,
  managerId: null,
  name: null,
  parentId: null,
  sortNo: 0,
  status: 'ENABLED',
  tenantId: 'default',
  type: null,
  website: null,
  zipcode: null,
}
