//This file is automatically generated

// basic-error-controller

import { BasicErrorController } from '@controller';
export default {
    actions: {
        [BasicErrorController.error.method] : {
            summary: 'error',
            method: 'get',
            url: (payload) => `/error`,
            parameters: [],
        },
        [BasicErrorController.error.method] : {
            summary: 'error',
            method: 'post',
            url: (payload) => `/error`,
            parameters: [],
        },
        [BasicErrorController.error.method] : {
            summary: 'error',
            method: 'put',
            url: (payload) => `/error`,
            parameters: [],
        },
        [BasicErrorController.error.method] : {
            summary: 'error',
            method: 'delete',
            url: (payload) => `/error`,
            parameters: [],
        },
        [BasicErrorController.errorHEAD.method] : {
            summary: 'error',
            method: 'head',
            url: (payload) => `/error`,
            parameters: [],
        },
        [BasicErrorController.errorOPTIONS.method] : {
            summary: 'error',
            method: 'options',
            url: (payload) => `/error`,
            parameters: [],
        },
        [BasicErrorController.errorPATCH.method] : {
            summary: 'error',
            method: 'patch',
            url: (payload) => `/error`,
            parameters: [],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
