//This file is automatically generated

// operation-handler

import { OperationHandler } from '@controller';
export default {
    actions: {
        [OperationHandler.handle.method] : {
            summary: 'handle',
            method: 'get',
            url: (payload) => `/actuator/health`,
            parameters: [{'in':'body','name':'body','description':'body','required':false,'schema':{'type':'object','additionalProperties':{'type':'string'}}}],
        },
        [OperationHandler.handle.method] : {
            summary: 'handle',
            method: 'get',
            url: (payload) => `/actuator/health/${payload.component}`,
            parameters: [{'in':'body','name':'body','description':'body','required':false,'schema':{'type':'object','additionalProperties':{'type':'string'}}}],
        },
        [OperationHandler.handle.method] : {
            summary: 'handle',
            method: 'get',
            url: (payload) => `/actuator/health/${payload.component}/${payload.instance}`,
            parameters: [{'in':'body','name':'body','description':'body','required':false,'schema':{'type':'object','additionalProperties':{'type':'string'}}}],
        },
        [OperationHandler.handle.method] : {
            summary: 'handle',
            method: 'get',
            url: (payload) => `/actuator/info`,
            parameters: [{'in':'body','name':'body','description':'body','required':false,'schema':{'type':'object','additionalProperties':{'type':'string'}}}],
        },
        [OperationHandler.handle.method] : {
            summary: 'handle',
            method: 'get',
            url: (payload) => `/actuator/loggers`,
            parameters: [{'in':'body','name':'body','description':'body','required':false,'schema':{'type':'object','additionalProperties':{'type':'string'}}}],
        },
        [OperationHandler.handle.method] : {
            summary: 'handle',
            method: 'get',
            url: (payload) => `/actuator/loggers/${payload.name}`,
            parameters: [{'in':'body','name':'body','description':'body','required':false,'schema':{'type':'object','additionalProperties':{'type':'string'}}}],
        },
        [OperationHandler.handle.method] : {
            summary: 'handle',
            method: 'post',
            url: (payload) => `/actuator/loggers/${payload.name}`,
            parameters: [{'in':'body','name':'body','description':'body','required':false,'schema':{'type':'object','additionalProperties':{'type':'string'}}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
