//This file is automatically generated

// web-mvc-links-handler

import { WebMvcLinksHandler } from '@controller';
export default {
    actions: {
        [WebMvcLinksHandler.links.method] : {
            summary: 'links',
            method: 'get',
            url: (payload) => `/actuator`,
            parameters: [],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
