//This file is automatically generated

// main-controller

import { MainController } from '@controller';
export default {
    actions: {
        [MainController.querySubRoleTemplates.method] : {
            summary: '单点登录成功后进入首页',
            method: 'get',
            url: (payload) => `/`,
            parameters: [],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
